version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    volumes:
      - ./:/var/www/html/

  composer:
    image: composer:1.8.3
    depends_on:
      - app
    volumes:
      - .:/app
    command: install --ignore-platform-reqs --no-scripts